export type RootStackParamList = {
  Login: undefined;
  Register: { role: 'driver' | 'guardian' | 'school' };
  DriverMain: undefined;
  DriverAttendance: undefined;
  DriverAttendanceDetail: { stopId: number; stopDescription: string; students: string[] };
  DriverRoute: undefined;
  DriverStudents: undefined;
  DriverProfile: undefined;
  DriverVehicle: undefined;
  DriverHistory: undefined;
  DriverHelp: undefined;
  DriverInvites: undefined;
  GuardianMain: undefined;
  GuardianTracking: undefined;
  GuardianDependents: undefined;
  GuardianDependentForm: { dependentId?: string } | undefined;
  GuardianPlans: undefined;
  GuardianProfile: undefined;
  GuardianHistory: undefined;
  GuardianHelp: undefined;
  GuardianSearchDriver: undefined;
  GuardianMonitoring: undefined;
  NoticeBoard: undefined;
  SchoolMain: undefined;
};
